version: '3'

services:
# uncomment if you want to use mariadb container, instead of local database mysql
#  db:
#    image: mariadb
#    container_name: nginx-nc-mariadb
#    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
#    restart: always
#    volumes:
#      - db:/var/lib/mysql
#    environment:
#      - MYSQL_ROOT_PASSWORD=
#    env_file:
#      - db.env

  redis:
    image: redis:alpine
    container_name: nginx-nc-redis
    restart: always
    networks:
      - nextcloud_nginx


  app:
#    build: ./smb
    image: gpopesc/nc-nginx-app
    container_name: nginx-nc-app
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /volume1/nextcloud:/var/www/html
    environment:
      - MYSQL_HOST=yoursqlserverip:port #usually: your_nas_server_ip:3306
      - MYSQL_PASSWORD=your-pass
      - MYSQL_DATABASE=your_database
      - MYSQL_USER=root
#      - MYSQL_PORT=3306
      - REDIS_HOST=redis
    depends_on:
#      - db
      - redis
    networks:
      - nextcloud_nginx


  web:
#    build: ./web
    image: gpopesc/nc-nginx-web
    container_name: nginx-nc-web
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    ports:
      - 5080:80
    volumes:
      - /volume1/nextcloud:/var/www/html:ro
#      - /volume1/nextcloud/data/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - app
    networks:
      - nextcloud_nginx


  cron:
    image: nextcloud:fpm-alpine
    container_name: nginx-nc-cron
    restart: always
    labels:
      - "com.centurylinklabs.watchtower.enable=false"
    volumes:
      - /volume1/nextcloud:/var/www/html
    entrypoint: /cron.sh
    depends_on:
#      - db
      - redis
    networks:
      - nextcloud_nginx


volumes:
#  db:
  nextcloud:

networks:
   nextcloud_nginx:
